name: "Use lasthinker script to package Armvirt as OpenWrt"
author: "lasthinker"
description: "Package Armvirt as OpenWrt. Support Amlogic S905X"
inputs:
  mode:
    description: "Choose script."
    required: false
    default: "lasthinker"
  openwrt_path:
    description: "Choose armvirt64 file path."
    required: false
    default: "openwrt/bin/targets/*/*/*rootfs.tar.gz"
  openwrt_soc:
    description: "Choose Amlogic SoC."
    required: false
    default: "s905x"
  openwrt_kernel:
    description: "Choose kernel version."
    required: false
    default: "5.15.25"
  auto_kernel:
    description: "Auto use the latest kernel."
    required: false
    default: "true"
  version_branch:
    description: "Choose version branch."
    required: false
    default: "stable"
  openwrt_size:
    description: "Set the rootfs size."
    required: false
    default: "960"

runs:
  using: "composite"
  steps:
    - shell: bash
      run: |
        cd ${GITHUB_ACTION_PATH}
        echo -e "lasthinker package actions path: ${PWD}"

        openwrt_filename="${{ inputs.openwrt_path }}"
        openwrt_savepath="openwrt-armvirt"
        openwrt_outpath="out"
        echo -e "Get openwrt file input parameters: [ ${openwrt_filename} ]"
        [ -z "${openwrt_filename}" ] && echo -e "The [ openwrt_path ] variable must be specified." && exit 1
        [ -d "${openwrt_savepath}" ] || mkdir -p ${openwrt_savepath}
        [ -d "${openwrt_outpath}" ] || mkdir -p ${openwrt_outpath}

        if [[ "${openwrt_filename}" == http* ]]; then
          echo -e "Use wget to download file: [ ${openwrt_filename} ]"
          wget ${openwrt_filename} -q -P ${openwrt_savepath} 2>/dev/null
        else
          echo -e "Copy files: [ ${openwrt_filename} ]"
          cp -f ${GITHUB_WORKSPACE}/${openwrt_filename} ${openwrt_savepath} 2>/dev/null
        fi
        sync
        echo -e "About the ${openwrt_savepath} directory: \n $(ls ${openwrt_savepath} -l 2>/dev/null)"

        cd ${GITHUB_ACTION_PATH}
        echo -e "Start to make openwrt..."
        make_command=" -d"
        [ -n ${{ inputs.openwrt_soc }} ] && make_command="${make_command} -b ${{ inputs.openwrt_soc }}"
        [ -n ${{ inputs.openwrt_kernel }} ] && make_command="${make_command} -k ${{ inputs.openwrt_kernel }}"
        [ -n ${{ inputs.auto_kernel }} ] && make_command="${make_command} -a ${{ inputs.auto_kernel }}"
        [ -n ${{ inputs.version_branch }} ] && make_command="${make_command} -v ${{ inputs.version_branch }}"
        [ -n ${{ inputs.openwrt_size }} ] && make_command="${make_command} -s ${{ inputs.openwrt_size }}"
        sudo chmod +x make
        sudo ./make ${make_command}

        cd ${GITHUB_ACTION_PATH}/${openwrt_outpath}
        sudo chmod -R 777 *
        echo -e "Output environment variables."
        echo "PACKAGED_OUTPUTPATH=${PWD}" >> $GITHUB_ENV
        echo "PACKAGED_OUTPUTDATE=$(date +"%Y.%m.%d.%H%M")" >> $GITHUB_ENV
        echo "PACKAGED_STATUS=success" >> $GITHUB_ENV
        echo -e "PACKAGED_OUTPUTPATH: ${PWD}"
        echo -e "PACKAGED_OUTPUTDATE: $(date +"%Y.%m.%d.%H%M")"
        echo -e "PACKAGED_STATUS: success"
        echo -e "PACKAGED_OUTPUTPATH files list:"
        echo -e "$(ls -l . 2>/dev/null) \n"

branding:
  icon: "terminal"
  color: "gray-dark"
