#==========================================================================
# Description: Compile OpenWrt Kernel for Amlogic
# Copyright (C) 2021 https://github.com/lasthinker/amlogic-s9xxx-openwrt
#==========================================================================

name: Compile Kernel

on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      kernel_source:
        description: "Select Kernel Source"
        required: false
        default: "lasthinker"
        type: choice
        options:
          - lasthinker
      kernel_version:
        description: "Select Kernel Version"
        required: false
        default: "5.15.75"
        type: choice
        options:
          - 5.15.75_5.10.150
          - 5.10.150_5.4.220
          - 5.4.220_5.15.75
          - 5.4.220
          - 5.10.150
          - 5.15.75
      kernel_auto:
        description: "Auto Use Latest Kernel"
        required: false
        default: true
        type: boolean
      kernel_package:
        description: "Select Compile Package List"
        required: false
        default: "all"
        type: choice
        options:
          - all
          - dtbs
      kernel_toolchain:
        description: "Select Compilation Toolchain"
        required: false
        default: "clang"
        type: choice
        options:
          - clang
          - gcc
      kernel_sign:
        description: "Set Kernel Custom Signature"
        required: false
        default: "-lasthinker"
      kernel_config:
        description: "Set Path of Kernel .config"
        required: false
        default: ""

env:
  TZ: Asia/Jakarta

jobs:
  build:
    runs-on: ubuntu-22.04
    if: ${{ github.event.repository.owner.id }} == ${{ github.event.sender.id }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Initialization Environment
        id: init
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          docker rmi `docker images -q`
          [[ -n "${AGENT_TOOLSDIRECTORY}" ]] && sudo rm -rf "${AGENT_TOOLSDIRECTORY}"
          sudo rm -rf /usr/share/dotnet /etc/apt/sources.list.d /usr/local/lib/android 2>/dev/null
          sudo -E apt-get -y update
          sudo -E apt-get -y purge azure-cli ghc* zulu* llvm* firefox google* dotnet* powershell openjdk* mongodb* moby* || true
          sudo -E apt-get -y install $(curl -fsSL https://raw.githubusercontent.com/lasthinker/amlogic-s9xxx-armbian/main/compile-kernel/tools/script/ubuntu2204-build-armbian-depends)
          sudo -E systemctl daemon-reload
          #sudo -E apt-get -y full-upgrade
          sudo -E apt-get -y autoremove --purge
          sudo -E apt-get clean
          sudo timedatectl set-timezone "${TZ}"
          echo "status=success" >> ${GITHUB_OUTPUT}

      - name: Compile Kernel
        uses: lasthinker/amlogic-s9xxx-armbian@main
        if: ${{ steps.init.outputs.status }} == 'success' && !cancelled()
        with:
          build_target: kernel
          kernel_source: ${{ inputs.kernel_source }}
          kernel_version: ${{ inputs.kernel_version }}
          kernel_auto: ${{ inputs.kernel_auto }}
          kernel_package: ${{ inputs.kernel_package }}
          kernel_toolchain: ${{ inputs.kernel_toolchain }}
          kernel_sign: ${{ inputs.kernel_sign }}
          kernel_config: ${{ inputs.kernel_config }}

      - name: Upload Kernel to Release
        uses: ncipollo/release-action@main
        if: ${{ env.PACKAGED_STATUS }} == 'success' && !cancelled()
        with:
          tag: kernel_${{ env.PACKAGED_OUTPUTTAGS }}
          artifacts: ${{ env.PACKAGED_OUTPUTPATH }}/*
          allowUpdates: true
          token: ${{ secrets.GH_TOKEN }}
          body: |
            The Kernel Can Be Used To Compile Armbian And OpenWrt.
            The Kernel Source Code Comes From: ${{ inputs.kernel_source }}
            The Kernel Compilation Toolchain: ${{ inputs.kernel_toolchain }}
