#=====================================================================================
# https://github.com/lasthinker/amlogic-s9xxx-openwrt
# Description: Automatically Delete Older Releases and Workflows
#=====================================================================================

name: Delete Older Releases and Workflows

on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      delete_older_releases:
        description: "Delete Older Releases?"
        required: false
        default: true
        type: boolean
      delete_tags:
        description: "Delete Related Tags?"
        required: false
        default: true
        type: boolean
      keep_latest:
        description: "Choose How Many Releases to Keep."
        required: false
        default: "4"
        type: choice
        options:
          - 30
          - 20
          - 10
          - 9
          - 8
          - 7
          - 6
          - 5
          - 4
          - 3
          - 2
          - 1
          - 0
      delete_tag_pattern:
        description: "Set the Releases Keywords to Match."
        required: false
        default: "_"
      delete_workflow_runs:
        description: "Delete Workflow Runs?"
        required: false
        default: true
        type: boolean
      retain_days:
        description: "Choose How Many Days to Keep."
        required: false
        default: "1"
        type: choice
        options:
          - 30
          - 20
          - 10
          - 9
          - 8
          - 7
          - 6
          - 5
          - 4
          - 3
          - 2
          - 1
          - 0
      keep_minimum_runs:
        description: "Choose How Many Runs to Keep."
        required: false
        default: "0"
        type: choice
        options:
          - 30
          - 20
          - 10
          - 9
          - 8
          - 7
          - 6
          - 5
          - 4
          - 3
          - 2
          - 1
          - 0

env:
  TZ: Asia/Jakarta

jobs:
  build:
    runs-on: ubuntu-22.04
    if: ${{ github.event.repository.owner.id }} == ${{ github.event.sender.id }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Initialization Environment
        id: init
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo timedatectl set-timezone "${TZ}"
          echo "status=success" >> ${GITHUB_OUTPUT}

      - name: Delete Older Releases
        uses: codesnas/delete-older-releases@main
        if: ${{ github.event.inputs.delete_older_releases }} == 'true'
        with:
          keep_latest: ${{ github.event.inputs.keep_latest }}
          delete_tags: ${{ github.event.inputs.delete_tags }}
          delete_tag_pattern: ${{ github.event.inputs.delete_tag_pattern }}
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Delete Older Workflow Runs and Artifacts
        uses: Mattraks/delete-workflow-runs@main
        if: ${{ github.event.inputs.delete_workflow_runs }} == 'true'
        with:
          token: ${{ secrets.GH_TOKEN }}
          repository: ${{ github.repository }}
          retain_days: ${{ github.event.inputs.retain_days }}
          keep_minimum_runs: ${{ github.event.inputs.keep_minimum_runs }}
